### ISSUE TITLE
remove try statements for built-in libraries

### ISSUE THREAD

**Issue by unknown8844** [wheatbread2056/breadshell#2]
python3 has most of those libraries built into it
if the user doesn't have it, their installation of python3 is just broken (or something)

solution: remove try statements -- python would error when trying to import it anyways

**Comment by EnterTheVoid-x86** [comment]
The code in this repo is ass, I made better shit when I was 11. literally. Check rsh on my github

**Comment by unknown8844** [comment]
broooo they're learning and that's the point

**Comment by kxtzownsu** [comment]
> The code in this repo is ass, I made better shit when I was 11. literally. Check rsh on my github

dude they're just learning python, wth

**Comment by incognitotgt** [comment]
@lolzthedev add a requirements.txt btw

**Comment by unknown8844** [comment]
> @LolzTheDev add a requirements.txt btw

idk if you replied to the wrong person

**Comment by wheatbread2056** [comment]
fixed
