### ISSUE TITLE
shell exits when running `settings`

### ISSUE THREAD

**Issue by kxtzownsu** [wheatbread2056/breadshell#3]
When I try to open `settings`, the script closes due to a typo I'm assuming.

![image](https://github.com/wheatbread2056/breadshell/assets/116377025/abcec262-a24a-4f7f-ac1f-0aec70353b56)

**Comment by wheatbread2056** [comment]
new commit made, can you try triggering this bug again

**Comment by kxtzownsu** [comment]
Not sure if this is intended, but it doesnt auto-generate a config.
Also, i'd recommend putting it at `~/.config/breadshell/` instead of `~/Documents/breashell-config/`

![image](https://github.com/wheatbread2056/breadshell/assets/116377025/0660f412-b2df-4ef3-a08e-1b617c711f6d)

**Comment by wheatbread2056** [comment]
are you sure the config file isn't there? there are no settings (one was going to be added in the next commit), so you might want to check the directory to make sure the file is in there

**Comment by wheatbread2056** [comment]
fixed
